const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const cutoffSchema = new mongoose.Schema({
    category: { type: String, required: true },
    cutoff_2022_r1: { type: String, default: null },
    cutoff_2022_r2: { type: String, default: null },
    cutoff_2022_r3: { type: String, default: null },
    cutoff_2023_r1: { type: String, default: null },
    cutoff_2023_r2: { type: String, default: null },
    cutoff_2023_r3: { type: String, default: null },
    cutoff_2024_r1: { type: String, default: null },
    cutoff_2024_r2: { type: String, default: null },
    cutoff_2024_r3: { type: String, default: null },
    cutoff_2025_r1: { type: String, default: null },
    cutoff_2025_r2: { type: String, default: null },
    cutoff_2025_r3: { type: String, default: null },
}, { _id: false });

const branchSchema = new mongoose.Schema({
    _id: { type: String }, // unique_key generated by pre-save hook
    public_id: { type: String, default: uuidv4, unique: true },
    college: { type: String, ref: 'College', required: true },
    cluster: { type: String, ref: 'Cluster', required: true },
    branch_id: { type: String, required: true },
    branch_name: { type: String, required: true },
    cutoffs: [cutoffSchema] // Embedded array for Cutoffs
}, {
    toJSON: {
        virtuals: true,
        transform: (_doc, ret) => {
            ret.unique_key = ret._id;
            return ret;
        }
    },
    toObject: {
        virtuals: true,
        transform: (_doc, ret) => {
            ret.unique_key = ret._id;
            return ret;
        }
    },
    _id: false // Disable auto _id since we define it manually
});

branchSchema.add({ _id: String });

branchSchema.pre('save', function (next) {
    if (this.isNew || !this._id) {
        // Reproduces `before_branch_insert` trigger behavior
        this._id = `${this.college}${this.cluster}${this.branch_id}`;
    }
    next();
});

module.exports = mongoose.model('Branch', branchSchema);
